language: node_js
node_js:
  - "lts/*"

cache:
  directories:
    - node_modules
    - elm-tests/elm-stuff/build-artifacts
    - sysconfcpus

install:
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

script:
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 npm run test:elm
  - npm run test:js

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

before_deploy:
  - node -e "console.log(require('./package.json').version)" > site/version.txt
  # quit if version matches latest in gh-pages
  - git fetch origin gh-pages:gh-pages
  - |
    git diff --exit-code gh-pages:version.txt site/version.txt
    export GIT_DIFF_EXIT_CODE=$?
    if [[ $GIT_DIFF_EXIT_CODE -ne 1 ]]
    then
      printf "Exit code was $GIT_DIFF_EXIT_CODE, Probably to publish a new version. Exiting.\n";
      exit 1;
    fi
  # build elm files
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 npm run build
  # stage built files
  - git add site/built -f
  - git add site/version.txt

deploy:
  local-dir: site
  provider: pages
  skip-cleanup: true
  github-token:
    secure: "geLH07dRroZ+Av+j+NC3ALWWg0hE+JJcniSUlRjT0PMlESMGdLF5bLNPd6tXzWELCPzphn+JhQSn3StJknE4hv1jw9CVmFhSTHlYeLpHHepOjAZvRKFy89FYW4uBkJGrYm61ZqgMdhuzVTVqXPmliJBl2XkrUw4yIkA4Vg8+/srwhCRU8rvKDkcx82p2GDPAccQaXpMQfY24GunoHOmeswJc8iGzkLWGpYzGSYOejtnBAVAt7O/6cNLXGbO0E0hiJWlOY7aM3ENZq1HnirSZPbnH+UcRWvdXZNHCenO1/zSqnUnyDzguhXrxy2Pu9HZziOxMrG7QmBti7ThFcHbHiioEdFekGUEi2LYAmgIaX98ag52q5M2Tg5Q2HnkABi2E1LL90ORJ7CQBMlLbquiSGxLMizuce95HJA+KsZ4SSkxi71oyLVdXUdHwsijFMFmY1y3uMaE/4+gBWflEPgui1g88OMHnxfWoj6OsNbbAKCrbRWUEvqESirytA7ORsMcUOqcLXm9gYqkI5gCihIzBGzUG64VNlYFxH/CZqCgkTz40gMa4jlDWMn7jgTOQLZLKIEoEL1BG9NrR++3TijLHTynvSJf4Gp+54HYHo2mo48fozPHKCugkdfVBsTTvC/qK5S1jGyMmFb+2+jfcMrGz2+AKoL79x1n4BVEzK8Y6kR0="
  keep-history: true
  on:
    branch: master
