language: node_js
node_js:
  - "lts"


before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start


cache:
  directories:
    - node_modules


script:
  - npm run lint
  - npm run test
  - npx codecov

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always