language: node_js
node_js:
  - "lts/*"

cache:
  directories:
    - node_modules
    - tests/elm-stuff/build-artifacts


script:
  - npm run test

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always